# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('cropdbid', models.TextField(db_column='cropdbid')),
                ('observationUnitDbId', models.TextField(db_column='observationunitdbid', primary_key=True, serialize=False)),
                ('studyDbId', models.TextField(db_column='studydbid')),
                ('studyName', models.TextField(db_column='studyname')),
                ('locationDbId', models.TextField(db_column='locationdbid')),
                ('locationName', models.TextField(db_column='locationname')),
                ('observationLevel', models.TextField(db_column='observationlevel')),
                ('observationLevels', models.TextField(db_column='observationlevels')),
                ('plotNumber', models.TextField(db_column='plotnumber')),
                ('plantNumber', models.TextField(db_column='plantnumber')),
                ('blockNumber', models.TextField(db_column='blocknumber')),
                ('replicate', models.TextField()),
                ('programName', models.TextField(db_column='programname')),
                ('germplasmDbId', models.TextField(db_column='germplasmdbid')),
                ('germplasmName', models.TextField(db_column='germplasmname')),
                ('X', models.TextField(db_column='x')),
                ('Y', models.TextField(db_column='y')),
                ('factor', models.TextField()),
                ('modality', models.TextField()),
                ('source', models.TextField()),
                ('observationUnitXref', models.TextField()),
                ('observations', models.TextField()),
                ('observationVariableDbId', models.TextField(db_column='observationvariabledbid')),
                ('season', models.TextField()),
                ('value', models.TextField()),
                ('observationTimestamp', models.TextField(db_column='observationtimestamp')),
                ('collector', models.TextField()),
            ],
            options={
                'db_table': 'phenotype',
                'managed': False,
            },
        ),
    ]
